### ISSUE TITLE
docker -- Error: Cannot find module 'multicast-dns'

### ISSUE THREAD

**Issue by gingerbreadassassin** [bjuretko/shelly-offline-ota-update#7]
First of all, thanks for this. It saved me from compromising on my network hardening.

With a fresh clone of the repository, 
`git clone https://github.com/bjuretko/shelly-offline-ota-update.git && cd shelly-offline-ota-update`

running
`sudo docker run -it --rm -v "$(pwd):/app" --network host node:12-alpine node /app/server.js`

results in:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'multicast-dns'
Require stack:
- /app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/server.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/server.js' ]
}
```

I'm not much of a js developer, let alone node, so I don't know the most appropriate place to fix this. However, I found a workaround:

`docker run -it --rm -v "$(pwd):/app" -w /app node:12-alpine npm install multicast-dns`

```
+ multicast-dns@7.2.5
added 33 packages from 24 contributors and audited 33 packages in 3.202s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

then:

`sudo docker run -it --rm -v "$(pwd):/app" --network host node:12-alpine node /app/server.js`

```
Downloaded /app/fw/20210115-103101_SHPLG-1.zip (20210115-103101/v1.9.4@e2732e05)
[...]
Downloaded /app/fw/20220811-152343_SHTRV-01_build.gbl (20220811-152343/v2.1.8@5afc928c)
Hostname: docker-desktop, IP4: 192.168.0.122
All IPs resolved: [{"address":"192.168.65.4","family":4}]
Listening on http://0.0.0.0:43563/
Waiting for shellys to appear ...
```

**Comment by bjuretko** [comment]
You are right,
please use this command with docker (it will install the deps)

```
docker run -it --rm -v "$(pwd):/app" --network host -w /app node:12-alpine npm run shelly-offline-ota-update
```
